### ISSUE TITLE
Feature: Create a GUI Interface to show updates.

### ISSUE THREAD

**Issue by pro-panda** [pro-panda/nalanda-cli#10]

**Comment by aditodkar** [comment]
Can I work on this issue. Can you suggest me which technologies should I use for making GUI.

**Comment by Pro-Panda** [comment]
Sure, you can start working. Go throught the code and Readme once to get an idea of how it works. I would suggest using the TKinter library for making the GUI.

**Comment by pro-panda** [comment]
GUI doesn't seem relevant at this point of time. CLI serves all the purposes well. Closing
